name: Pylint Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Pylint
      run: pip install pylint==3.3.5

    - name: Clean the cache
      run: |
        echo "Clearing Pylint cache..."
        pylint --clear-cache-post-run=y
        echo "Pylint cache cleared successfully"

    - name: Run Pylint analysis
      id: pylint
      run: |
        # Run Pylint using project's .pylintrc and save output
        pylint_output=$(pylint --exit-zero mymodels/core/*)
        echo "Pylint output:"
        echo "$pylint_output"

        # Extract score and judge
        score=$(echo "$pylint_output" | grep -oP 'Your code has been rated at \K\d+\.?\d*')
        if (( $(echo "$score < 6" | bc -l) )); then
          echo "::error::Pylint score ${score}/10 is below the requirement (minimum 6 points)"
          exit 1
        else
          echo "Pylint score ${score}/10 meets the requirement"
        fi