name: Push Tags and Create Release

on:
  push:
    branches:
      - main

jobs:
  push_tags_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # This ensures all tags are fetched
          token: ${{ secrets.PAT_TOKEN }}  # Use PAT instead of GITHUB_TOKEN

      - name: Push tags
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Get latest tag
        id: latest_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT

      - name: Check if release exists
        id: check_release
        run: |
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ steps.latest_tag.outputs.tag }}")
          RELEASE_ID=$(echo "$RELEASE_INFO" | jq -r '.id // "null"')
          if [ "$RELEASE_ID" != "null" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.latest_tag.outputs.tag }}
          release_name: Release ${{ steps.latest_tag.outputs.tag }}
          body: |
            Changes in this Release:
            ${{ steps.latest_tag.outputs.commit_message }}
          draft: false
          prerelease: false
          
      - name: Update Existing Release
        if: steps.check_release.outputs.exists == 'true'
        run: |
          PREVIOUS_BODY=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/${{ steps.check_release.outputs.release_id }}" | jq -r '.body')
          
          NEW_BODY=$(cat <<EOF
          $PREVIOUS_BODY
          
          Update from commit on $(date +"%Y-%m-%d %H:%M:%S"):
          ${{ steps.latest_tag.outputs.commit_message }}
          EOF
          )
          
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": $(echo "$NEW_BODY" | jq -s -R .)}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/releases/${{ steps.check_release.outputs.release_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}