name: Update GitHub Wiki

on:
  push:
    branches: [ main, master ]
    paths:
      - 'wiki/**'

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source
          
      - name: Checkout wiki repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki-repo
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Copy wiki files
        run: |
          cp -r source/wiki/* wiki-repo/
          
      - name: Commit and push changes
        working-directory: wiki-repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Update wiki from repository changes"
          git push
