name: Update GitHub Wiki
run-name: ${{ github.actor }} is updating the GitHub Wiki
on:
  push:
jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Clone Wiki
        run: |
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki-repo
          
      - name: Copy Wiki Content
        run: |
          cp -r wiki/* wiki-repo/
          
      - name: Push to Wiki
        working-directory: wiki-repo
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update wiki content from wiki directory"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git master
